### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by tuxpeople** [neochrome/docker-bastion#3]
Hi Johan

Would you mind to provide multi-arch images? I'd like to run it on on a Raspberry Pi 4 based Kubernetes Cluster and would need an arm64 image. I was successfull to build it as it is right now as multiarch image for amd64, arm64, armv6 and armv7:

https://hub.docker.com/repository/docker/tdeutsch/bastion/tags?page=1&ordering=last_updated

But I prefer to add this to you as "upstream", because I don't see a benefit in manually rebuilding your image :-)

Let me know what you think and also let me know if you need help for a multi-arch build pipeline.

Br
Thomas

**Comment by neochrome** [comment]
Hi, glad to hear you find the project useful!
I think multi-arch support sounds like a great idea, and will try to take a
look at it soonish. Btw, do you know if docker gub builds have support for
this, or if it is time to move the image building to GH actions instead?

**Comment by tuxpeople** [comment]
I personally use GitHub Actions for this. This is a stripped down version of what I use:

```
name: ci

# This worflow needs those repository secrets:
#
# DOCKERHUB_USERNAME = Docker Hub username
# DOCKERHUB_TOKEN = Docker Hub token

on:
  push:
    branches: [master, main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          push: true
          tags: neochrome/bastion:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
```

Above is untested, but should work. This is my current workflow:
https://github.com/tuxpeople/docker-bastion/blob/master/.github/workflows/release.yml

This would be the bare minimum:
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

BTW: Another interesting thing is dependabot. It makes pull requests for updates of dependencies. I use it for updates to the base images of my docker images:
https://github.com/tuxpeople/docker-bastion/blob/master/.github/dependabot.yaml

More infos: https://docs.github.com/en/github/administering-a-repository/about-dependabot-version-updates
